### ISSUE TITLE
Using linux gives 'AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by 00ninja** [tzlion/frogtool#3]
I am having issues running frogtool.py under Linux Mint 20.3 using python 3.10+ and Pillow 9.5.0.

Running 'python3 frogtool.py /dev/mmcblk0 FC' gives following error:

`Traceback (most recent call last):`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 18, in <module>
    if ctypes.windll:`
`AttributeError: module 'ctypes' has no attribute 'windll'`

Running 'python3 frogtool.py /dev/mmcblk0p1/ FC' gives same error.

It was suggested to temporarily comment out the 2 lines referercing windll. After completing this, it does run without error but after running 'python3 frogtool.py /dev/mmcblk0 FC' I get the following prompt:

`frogtool v0.2.0`
`! Specified drive or path is not accessible`
`Please enter the drive or path where your SF2000 SD card is located e.g. F:`
    
Running 'python3 frogtool.py /dev/mmcblk0p1/ FC' gives same prompt. 

Files on /dev/mmcblk0 can be accessed via file browser without problem. It seems to be looking for a Windows drive letter rather than a linux drive path.

**Comment by EvanClements** [comment]
Just some thoughts:

I wonder if PathLib can be used instead of os.path? That way the path handling (especially with the difference between Windows and Linux) can be abstracted out.

I wonder if this is a permissions issue? How would we test that. If it's just checking for whether something is a directory or not, you might be able to try putting in a folder in your home directory to see if it can access that. 

I'll do some testing later.

**Comment by 00ninja** [comment]
> Another thought: does your SD card have a mount point? Usually found in /media/ or /mnt/

While I did not specifically mount it from cli, inserting the card auto-mounts and shows up in /media/ as "/media/00ninja/C2A6-503B"

**Comment by 00ninja** [comment]
> Have you tried using that for the drive input instead of /dev/mmcblk0?
> 
> My theory is that the /dev/ path points to the device, but not the mounted filesystem that you see in your file explorer.

Ok, good catch! I had not tried that path, but just did with a stock copy of 5/15 firmware (without any zips and images) and it did see the total amount of files and did overwrite changes to 3 files in /Resources. So far a partial success!

Next I will remove those original files (keeping bios and resources) and put in my images and zips and test again later this morning.

**Comment by EvanClements** [comment]
Awesome! Let us know how it goes

**Comment by 00ninja** [comment]
Well I thought it was

**Comment by 00ninja** [comment]
> Awesome! Let us know how it goes

Sorry, closed the issue lol. Ok re-opened.

So it did not go well when I replaced the original files on SD card with my zips and images. Basically I now get the same error as the Windows 10 VirtualBox attempt, which I added as a separate issue. Here is the error in Linux Mint:

`Processing FC`
`Looking for files in /media/00ninja/C2A6-503B/FC`
`Found image and zip files, looking for matches to combine to zfc`
`Traceback (most recent call last):`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 375, in <module> run()`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 363, in run process_sys(drive, syskey, test_mode)`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 111, in process_sys convert_zip_image_pairs_to_zxx(roms_path, system)`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 167, in convert_zip_image_pairs_to_zxx converted = convert_zip_image_to_zxx(roms_path, img_file, zip_file, sys_zxx_ext)`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 184, in convert_zip_image_to_zxx converted = rgb565_convert(img_file_path, zxx_file_path, (144, 208))`
`File "/home/00ninja/Downloads/datafrog/fixes & tools/frogtool-0.2.0-py/frogtool.py", line 233, in rgb565_convert r = pixels[w, h][0] >> 3`
`TypeError: 'int' object is not subscriptable`

**Comment by 00ninja** [comment]
While the Windows 10 VirtrualBox attempt DID convert 46 zips and images to .zfc files before it gives the same TypeError, only created one .zfc file in Linux Mint plus an extra 0byte file.

**Comment by tzlion** [comment]
Closing since the windll issue was fixed by #2 & we can keep discussion of the TypeError in #4

**Comment by tzlion** [comment]
Fix is in v0.2.1 https://github.com/tzlion/frogtool/releases/tag/v0.2.1
